### ISSUE TITLE
Multiple values for a child object

### ISSUE THREAD

**Issue by Dylan-vo** [ktbyers/ansible_helpers#2]
- name: Execute show run
      ios_command:
        commands:
          - show run
      register: show_run
    - name: Use confparse_parent filter to trunk ports 
       set_fact: 
         intfs: "{{ show_run | confparse_parent(parent='^interface', child='dylan | trunk') }}" 

Gives me the error:  "Currently only a single child match is supported" 

Is there any way to achieve multiple child matches using this helper?

**Comment by ktbyers** [comment]
This library is largely dead...i.e. I am not really maintaining it any longer.


Regards, Kirk
